name: Bug反馈
about: 报个Bug
title: ''
labels: bug
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        欢迎来到 LLOneBot 的 Issue Tracker！请填写以下表格来提交 Bug。
  - type: input
    id: system-version
    attributes:
      label: 系统版本
      description: 运行 QQNT 的系统版本
      placeholder: Windows 10 Pro Workstation 22H2
    validations:
      required: true
  - type: input
    id: qqnt-version
    attributes:
      label: QQNT 版本
      description: 可在 QQNT 的「关于」或是在 LiteLoaderQQNT 的设置页中找到
      placeholder: 9.9.7-21804
    validations:
      required: true
  - type: input
    id: llonebot-version
    attributes:
      label: LLOneBot 版本
      description: 可在 LiteLoaderQQNT 的设置页或是 QQNT 的设置也侧栏中找到
      placeholder: 3.18.0
    validations:
      required: true
  - type: input
    id: onebot-client-version
    attributes:
      label: OneBot 客户端
      desctiption: 连接至 LLOneBot 的客户端版本信息
      placeholder: Overflow 2.16.0-2cf7991-SNAPSHOT
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么?
      description: 填写你认为的 LLOneBot 的不正常行为
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 如何复现
      description: 填写应当如何操作才能触发这个不正常行为
      placeholder: |
        1. xxx
        2. xxx
        3. xxx
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: 期望的结果?
      description: 填写你认为 LLOneBot 应当执行的正常行为
    validations:
      required: true
  - type: textarea
    id: llonebot-log
    attributes:
      label: LLOneBot 运行日志
      description: 在 LLOneBot 的设置页中打开「写入日志」然后粘贴相关日志内容到此处
  - type: textarea
    id: onebot-client-log
    attributes:
      label: OneBot 客户端运行日志
      description: 粘贴 OneBot 客户端的相关日志内容到此处
